In [1]:
# ============================================================
# Notebook path setup
# ============================================================
# Purpose:
# - make the project root importable from inside the notebooks folder
# - allow imports such as `from training.dataset import ...`
# ============================================================

from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Project root added to sys.path:")
print(PROJECT_ROOT)

Project root added to sys.path:
/Users/AKB_CIM/DS_HQ/projects/global-demand-forecasting

In [2]:
from training.dataset import load_full_modeling_dataset

df = load_full_modeling_dataset()

print(df.shape)
df.head()

(2744100, 23)

,id,item_id,dept_id,cat_id,store_id,state_id,d,date,wm_yr_wk,sales,...,precipitation_sum,wind_speed_10m_max,cpi_all_items,unemployment_rate,federal_funds_rate,nonfarm_payrolls,trends_walmart,trends_grocery_store,trends_discount_store,trends_cleaning_supplies
0,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1824,2016-01-26,11552,1,...,0.0,6.0,237,4,0,143210,49,46,57,62
1,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1825,2016-01-27,11552,1,...,0.0,7.2,237,4,0,143210,51,46,55,73
2,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1826,2016-01-28,11552,2,...,0.0,11.2,237,4,0,143210,51,46,49,68
3,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1827,2016-01-29,11552,1,...,0.0,6.2,237,4,0,143210,52,46,57,76
4,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1828,2016-01-30,11601,0,...,8.2,9.2,237,4,0,143210,68,57,83,45

In [3]:
df.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,date,wm_yr_wk,sales,...,precipitation_sum,wind_speed_10m_max,cpi_all_items,unemployment_rate,federal_funds_rate,nonfarm_payrolls,trends_walmart,trends_grocery_store,trends_discount_store,trends_cleaning_supplies
0,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1824,2016-01-26,11552,1,...,0.0,6.0,237,4,0,143210,49,46,57,62
1,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1825,2016-01-27,11552,1,...,0.0,7.2,237,4,0,143210,51,46,55,73
2,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1826,2016-01-28,11552,2,...,0.0,11.2,237,4,0,143210,51,46,49,68
3,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1827,2016-01-29,11552,1,...,0.0,6.2,237,4,0,143210,52,46,57,76
4,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1828,2016-01-30,11601,0,...,8.2,9.2,237,4,0,143210,68,57,83,45

In [4]:
df.shape

(2744100, 23)

In [5]:
# ============================================================
# Basic dataset diagnostics
# ============================================================

print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nUnique series (store_id, item_id):")
print(df.groupby(["store_id", "item_id"]).ngroups)

print("\nDate range:")
print(df["date"].min(), "→", df["date"].max())

print("\nMemory usage (MB):")
print(df.memory_usage(deep=True).sum() / 1_000_000)

df.head()

Rows: 2744100
Columns: 23

Unique series (store_id, item_id):
30490

Date range:
2016-01-26 → 2016-04-24

Memory usage (MB):
3132.774232

,id,item_id,dept_id,cat_id,store_id,state_id,d,date,wm_yr_wk,sales,...,precipitation_sum,wind_speed_10m_max,cpi_all_items,unemployment_rate,federal_funds_rate,nonfarm_payrolls,trends_walmart,trends_grocery_store,trends_discount_store,trends_cleaning_supplies
0,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1824,2016-01-26,11552,1,...,0.0,6.0,237,4,0,143210,49,46,57,62
1,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1825,2016-01-27,11552,1,...,0.0,7.2,237,4,0,143210,51,46,55,73
2,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1826,2016-01-28,11552,2,...,0.0,11.2,237,4,0,143210,51,46,49,68
3,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1827,2016-01-29,11552,1,...,0.0,6.2,237,4,0,143210,52,46,57,76
4,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,d_1828,2016-01-30,11601,0,...,8.2,9.2,237,4,0,143210,68,57,83,45